[2025-05-15T08:39:28.139+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_pipeline_dag.run_dbt_models manual__2025-05-15T08:34:24.113035+00:00 [queued]>
[2025-05-15T08:39:28.151+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_pipeline_dag.run_dbt_models manual__2025-05-15T08:34:24.113035+00:00 [queued]>
[2025-05-15T08:39:28.151+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T08:39:28.151+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2025-05-15T08:39:28.151+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T08:39:28.169+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-05-15 08:34:24.113035+00:00
[2025-05-15T08:39:28.174+0000] {standard_task_runner.py:55} INFO - Started process 259 to run task
[2025-05-15T08:39:28.179+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline_dag', 'run_dbt_models', 'manual__2025-05-15T08:34:24.113035+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpb83hye0j']
[2025-05-15T08:39:28.181+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask run_dbt_models
[2025-05-15T08:39:28.276+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_pipeline_dag.run_dbt_models manual__2025-05-15T08:34:24.113035+00:00 [running]> on host 0ae4d98d4859
[2025-05-15T08:39:28.389+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=epsi_data_team
AIRFLOW_CTX_DAG_ID=sales_pipeline_dag
AIRFLOW_CTX_TASK_ID=run_dbt_models
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T08:34:24.113035+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T08:34:24.113035+00:00
[2025-05-15T08:39:28.390+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T08:39:28.392+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /workspace/dbt && dbt run']
[2025-05-15T08:39:28.408+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T08:39:28.410+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /workspace/dbt: No such file or directory
[2025-05-15T08:39:28.410+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-15T08:39:28.422+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-15T08:39:28.425+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_pipeline_dag, task_id=run_dbt_models, execution_date=20250515T083424, start_date=20250515T083928, end_date=20250515T083928
[2025-05-15T08:39:28.437+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 259)
[2025-05-15T08:39:28.481+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T08:39:28.501+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
